### ISSUE TITLE
Creating additional works after depositing a work gives "no method error" message 

### ISSUE THREAD

**Issue by rjkati** [samvera-labs/nurax-pg#23]
### Descriptive summary
I am able to create one work as a valkyrie resource on nurax-pg. However, when I navigate back to the Works page to create an additional work, I get a "NoMethodError" message and cannot proceed further.

URL: https://nurax-pg.curationexperts.com/dashboard/my/works?locale=en

### Expected behavior
I should be able to create additional works after depositing a work.

### Actual behavior
When I navigate to the works page after depositing a work, I get a "NoMethodError" message.

### Steps to reproduce the behavior

1. Login to nurax-pg
2. Dashboard -> Works -> Add new work
3. Select any Work Type
4. Fill in required steps
5. Save
6. Navigate to Dashboard -> Works
7. Observe error message
![nomethoderror-works](https://user-images.githubusercontent.com/32644254/140410099-6d474544-f94f-4c29-bacd-b4e6c3da466a.PNG)

**Comment by elrayle** [comment]
I turned off the ability to transfer works (temporarily).  That code is still using ActiveFedora, which led to the failure.  You should be able to test works again.

I'm leaving the issue open.

### Remaining work

Fix [Hyrax Issue #5247](https://github.com/samvera/hyrax/issues/5247) and turn Transfer work flipper back on.

**Comment by jlhardes** [comment]
Transfer works is enabled on nurax-pg and I can follow these steps to create a Work and then come back to Dashboard > Works and there is no longer an error message. Closing this issue as fixed.
