### ISSUE TITLE
Saving a new admin set raises `undefined internal_reosurce`

### ISSUE THREAD

**Issue by elrayle** [samvera-labs/nurax-pg#28]
### Descriptive summary

When using the postgres adapter in nurax-pg, creating an admin set through the new admin set form raises `undefined internal_resource` when the admin set is saved.

### Rationale

Editing should work for wings adapter and non-wings adapters.

### Expected behavior

Creating and saving a new Admin Set with the postgres adapter fully saves the new admin set.

### Actual behavior

Creating and saving a new Admin Set with the postgres adapter raises an exception.

![image](https://user-images.githubusercontent.com/6855473/140584519-f27f9660-a552-4c31-94b4-7114cdf8d254.png)

### Steps to reproduce the behavior

1. Login to [nurax-pg](https://nurax-pg.curationexperts.com)
1. Dashboard -> [Collections](https://nurax-pg.curationexperts.com/dashboard/my/collections?locale=en) -> New Collection
2. Select Admin Set
2. Fill in required metadata
3. Save

raises an exception

### Related work

Issue https://github.com/samvera/hyrax/issues/5130 - Val MVP: Create AdministrativeSet as a valkyrie resource through UI

**Comment by gamontoya** [comment]
@jlhardes I can't test this since I don't have Admin Set as one of the collection type options.

**Comment by jlhardes** [comment]
I can create and edit an Admin Set on nurax-pg so this is working. Closing as fixed!
