### ISSUE TITLE
Fileset not in work show page listing of uploaded files

### ISSUE THREAD

**Issue by elrayle** [samvera-labs/nurax-pg#29]
### Descriptive summary

Using a nurax-pg adapter, after creating a work with an uploaded file, the file is not in the uploaded files list.  It has not been confirmed whether the File was uploaded and the FileSet created.  

### Expected behavior

A work that was created with an uploaded form should show the file in the list of uploaded file on the work show page.

### Actual behavior

A work that was created with an uploaded form does not show the file in the list of uploaded file on the work show page.

![image](https://user-images.githubusercontent.com/6855473/140585111-cc435990-7968-44ca-beb0-1358e60b8e27.png)

### Steps to reproduce the behavior

1. Login to [nurax-pg](https://nurax-pg.curationexperts.com)
1. Dashboard -> [Works](https://nurax-pg.curationexperts.com/dashboard/my/works?locale=en)
2. Click Add new work
2. Select Generic Work
3. Fill in required metadata
4. Add a file
4. Save

Forwards to work show page, but doesn't list the uploaded file in the Items section.

### Related work

Issue https://github.com/samvera/hyrax/issues/5136 - Val MVP: Create Hyrax::FileSet as a valkyrie resource through UI

**Comment by gamontoya** [comment]
@jlhardes This is **closeable**. I cannot replicate the issue.

**Comment by jlhardes** [comment]
I think we still have some problems with derivative generation to get appropriate thumbnail images accompanying the file list but this issue with files not being listed is fixed. Closing!
