### ISSUE TITLE
creating a new collection does not give confirmation message

### ISSUE THREAD

**Issue by rjkati** [samvera-labs/nurax-pg#31]
When I fill out the form to create a new collection on nurax-pg and click "save", the page does not display a confirmation message or give me the option to enter additional metadata. If I click on the "Collections" tab after creating the collection, I can see the new collection in the "Your Collections" list.

### Expected Behavior

Nurax-pg should behave like nurax-dev in regards to creating collections. When I create a collection, a message confirming that the collection was successfully created should display. The page should reload with additional metadata fields.

### Steps to reproduce:

1. Go to nurax-pg
2. Navigate to Dashboard -> Collections
3. Click "New Collection" button
4. Select "User Collection" and click "Create Collection"
5. Fill in metadata and click "save"
6. Observe that save button is grayed out, but no confirmation message is displayed and page does not reload to display additional metadata fields.

**Comment by gamontoya** [comment]
@jlhardes This is **closeable**. I cannot replicate this reported issue.

- New collection created
- Green banner displays: Collection was successfully created.
- Additional metadata filed display

**Comment by jlhardes** [comment]
Closing as fixed!
