### ISSUE TITLE
Highlighting work on profile gives "ArgumentError in Hyrax::Dashboard::Profiles#show"

### ISSUE THREAD

**Issue by rjkati** [samvera-labs/nurax-pg#35]
### Description of Issue
After selecting a work to highlight on my user profile, nurax-pg gives an error on my profile page: "ArgumentError in Hyrax::Dashboard::Profiles#show" If I remove the highlighted work from my profile, I can access my profile page without issue.

### Steps to Reproduce

1. Go to Dashboard -> Works
2. In the Actions menu for one of your works, select "Highlight Work on Profile"
3. Go to Dashboard -> Your Activity -> Profile
4. Observe error message
![profile_error](https://user-images.githubusercontent.com/32644254/144432328-858c3468-9eef-4ebf-8a9c-cc8711b2d64e.PNG)

**Comment by gamontoya** [comment]
@jlhardes This is **closeable**. I was not able to replicate. Worked for `public` as well as `private` work.

![Highlight](https://user-images.githubusercontent.com/4314914/188751001-311a390f-849b-47d8-82d0-8ae61c83a6ea.png)

**Comment by jlhardes** [comment]
Closing as fixed!
