### ISSUE TITLE
Clicking "collections created" on user profile page gives "ActionView::MissingTemplate in Catalog#index" error

### ISSUE THREAD

**Issue by rjkati** [samvera-labs/nurax-pg#37]
Description of issue
When I click "Collections created" on my user profile page, nurax-pg gives me a "ActionView::MissingTemplate in Catalog#index" error message.

Steps to replicate

1. Navigate to Dashboard -> Your Activity -> Profile
2. Click on "Collections created" link.
3. Observe error message.
![profilecollectionerror](https://user-images.githubusercontent.com/32644254/144458145-50630f9e-4083-42cb-a23c-20c92529cd39.PNG)

**Comment by gamontoya** [comment]
@jlhardes Can be **closed;** I cannot replicate.

![activProf](https://user-images.githubusercontent.com/4314914/188751495-c2a027a6-5b99-4f0d-aea6-7c969e7f4359.png)

**Comment by jlhardes** [comment]
Closing as fixed!
